server:
  port: 52000

spring:
  application:
    name: server-one

  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        service: server-one
        namespace: a443294f-34f1-4ad9-8ab8-373414c1161a
        group: dev
        server-addr: http://127.0.0.1:8848

logging:
  level:
    org:
      springframework:
        web: DEBUG
